#!/bin/bash
arecord -D front:CARD=CODEC,DEV=0 -f S16_LE -V mono --rate=11025 >./source.raw  &
tail -f ./source.wav | ffmpeg -f s16le -i pipe:0 -map 0 -codec:v libx264 -codec:a libfaac -f ssegment -segment_list playlist.m3u8 -segment_time 10 out%03d.ts

